# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/95a1ff68-cdcb-4ebf-9c1a-19b62f54dbf4";
      fsType = "btrfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/29C3-C347";
      fsType = "vfat";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/9c50037a-c4d0-4c5e-9c8d-90f5d5ee7ec8";
      fsType = "ext4";
    };

  fileSystems."/home/noaccos/Games/Genshin Impact" =
    { device = "/dev/disk/by-uuid/849be182-2083-4002-9a55-38e3546a4ca4";
      fsType = "btrfs";
      depends = [ "/home" ];
    };

  swapDevices = [ ];

  services.xserver = {
    exportConfiguration = true;
    monitorSection = ''
      VendorName     "Unknown"
      ModelName      "HPN OMEN by HP 35"
      HorizSync       73.0 - 151.0
      VertRefresh     30.0 - 100.0
      Option         "DPMS"
    '';
    screenSection = ''
      DefaultDepth    24
      Option         "Stereo" "0"
      Option         "nvidiaXineramaInfoOrder" "DFP-6"
      Option         "metamodes" "DP-4: 3440x1440_100 +1920+0 {ForceCompositionPipeline=On, ForceFullCompositionPipeline=On}, HDMI-0: 1920x1080_60 +0+360 {ForceCompositionPipeline=On, ForceFullCompositionPipeline=On}"
      Option         "SLI" "Off"
      Option         "MultiGPU" "Off"
      Option         "BaseMosaic" "off"
      '';
      };

}
